package com.limagiran.campominado.view;

import static com.limagiran.campominado.settings.Settings.EnumMode.*;
import static com.limagiran.campominado.settings.Settings.set;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ResourceBundle;
import javax.swing.AbstractAction;
import javax.swing.BorderFactory;
import javax.swing.InputMap;
import javax.swing.JButton;
import static javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Vinicius Silva
 */
public class Records extends JDialog {

    /**
     * Creates new form Records
     */
    private Records() {
        initComponents();
        inserirAtalhos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRecords = new JPanel();
        jLabelRecordEasy = new JLabel();
        jLabelRecordEasyPoints = new JLabel();
        jLabelRecordEasyName = new JLabel();
        jLabelRecordMedium = new JLabel();
        jLabelRecordMediumPoint = new JLabel();
        jLabelRecordMediumName = new JLabel();
        jLabelRecordHard = new JLabel();
        jLabelRecordHardPoints = new JLabel();
        jLabelRecordHardName = new JLabel();
        jButtonOk = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new AbsoluteLayout());

        ResourceBundle bundle = ResourceBundle.getBundle("com/limagiran/campominado/view/Bundle"); // NOI18N
        jPanelRecords.setBorder(BorderFactory.createTitledBorder(null, bundle.getString("Records.jPanelRecords.border.title"), TitledBorder.CENTER, TitledBorder.TOP, new Font("Bookman Old Style", 0, 24))); // NOI18N
        jPanelRecords.setToolTipText(null);
        jPanelRecords.setLayout(new AbsoluteLayout());

        jLabelRecordEasy.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordEasy.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordEasy.setText(bundle.getString("Records.jLabelRecordEasy.text")); // NOI18N
        jLabelRecordEasy.setToolTipText(null);
        jPanelRecords.add(jLabelRecordEasy, new AbsoluteConstraints(10, 70, 90, 30));

        jLabelRecordEasyPoints.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordEasyPoints.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordEasyPoints.setText(set.getRecord(EASY));
        jLabelRecordEasyPoints.setToolTipText(null);
        jPanelRecords.add(jLabelRecordEasyPoints, new AbsoluteConstraints(100, 70, 70, 30));

        jLabelRecordEasyName.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordEasyName.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordEasyName.setText(set.getRecordName(EASY));
        jLabelRecordEasyName.setToolTipText(null);
        jPanelRecords.add(jLabelRecordEasyName, new AbsoluteConstraints(180, 70, 210, 30));

        jLabelRecordMedium.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordMedium.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordMedium.setText(bundle.getString("Records.jLabelRecordMedium.text")); // NOI18N
        jLabelRecordMedium.setToolTipText(null);
        jPanelRecords.add(jLabelRecordMedium, new AbsoluteConstraints(10, 110, 90, 30));

        jLabelRecordMediumPoint.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordMediumPoint.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordMediumPoint.setText(set.getRecord(MEDIUM));
        jLabelRecordMediumPoint.setToolTipText(null);
        jPanelRecords.add(jLabelRecordMediumPoint, new AbsoluteConstraints(100, 110, 70, 30));

        jLabelRecordMediumName.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordMediumName.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordMediumName.setText(set.getRecordName(MEDIUM));
        jLabelRecordMediumName.setToolTipText(null);
        jPanelRecords.add(jLabelRecordMediumName, new AbsoluteConstraints(180, 110, 210, 30));

        jLabelRecordHard.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordHard.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordHard.setText(bundle.getString("Records.jLabelRecordHard.text")); // NOI18N
        jLabelRecordHard.setToolTipText(null);
        jPanelRecords.add(jLabelRecordHard, new AbsoluteConstraints(10, 150, 90, 30));

        jLabelRecordHardPoints.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordHardPoints.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordHardPoints.setText(set.getRecord(HARD));
        jLabelRecordHardPoints.setToolTipText(null);
        jPanelRecords.add(jLabelRecordHardPoints, new AbsoluteConstraints(100, 150, 70, 30));

        jLabelRecordHardName.setFont(new Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabelRecordHardName.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelRecordHardName.setText(set.getRecordName(HARD));
        jLabelRecordHardName.setToolTipText(null);
        jPanelRecords.add(jLabelRecordHardName, new AbsoluteConstraints(180, 150, 210, 30));

        jButtonOk.setFont(new Font("Bookman Old Style", 0, 14)); // NOI18N
        jButtonOk.setText(bundle.getString("Records.jButtonOk.text")); // NOI18N
        jButtonOk.setToolTipText(null);
        jButtonOk.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanelRecords.add(jButtonOk, new AbsoluteConstraints(150, 190, 80, -1));

        getContentPane().add(jPanelRecords, new AbsoluteConstraints(0, 0, 400, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    /**
     * Cria e exibe a janela de recordes
     */
    public static void main() {
        SwingUtilities.invokeLater(() -> {
            new Records().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonOk;
    private JLabel jLabelRecordEasy;
    private JLabel jLabelRecordEasyName;
    private JLabel jLabelRecordEasyPoints;
    private JLabel jLabelRecordHard;
    private JLabel jLabelRecordHardName;
    private JLabel jLabelRecordHardPoints;
    private JLabel jLabelRecordMedium;
    private JLabel jLabelRecordMediumName;
    private JLabel jLabelRecordMediumPoint;
    private JPanel jPanelRecords;
    // End of variables declaration//GEN-END:variables

    /**
     * Insere os atalhos da janela atual
     */
    public final void inserirAtalhos() {
        
        InputMap inputMap = getRootPane().getInputMap(WHEN_IN_FOCUSED_WINDOW);
        getRootPane().setInputMap(WHEN_IN_FOCUSED_WINDOW, inputMap);

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "esc");

        getRootPane().getActionMap().put("esc", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                dispose();
            }
        });
    }
}
